spring:
  application:
    name: Jwt, Mongodb, Angular

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/jwt
      repositories:
        type: IMPERATIVE

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  access-token-validity: 60000
  access-token-key: kimbsAt
  access-token-cookie-name: accessToken

  refresh-token-key: kimbsRt
  refresh-token-expiration-validity: 60000
  refresh-token-cookie-name: refreshToken