spring:
  application:
    name: Jwt, Mongodb, Angular

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/jwt
      repositories:
        type: IMPERATIVE

#      org.springframework.data.mapping.model.CamelCaseAbbreviatingFieldNamingStrategy;
#      org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy;
#      org.springframework.data.mapping.model.CamelCaseSplittingFieldNamingStrategy;
#      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
