spring:
  application:
    name: Jwt, Mongodb, Angular

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/jwt
      repositories:
        type: IMPERATIVE

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  token-validity: 60000
  secret-key: kimbs